### ISSUE TITLE
Support `build.gradle.kts` as the gradle file name without additional configuration

### ISSUE THREAD

**Issue by moormaan** [CircleCI-Public/circleci-orbs#180]
### Expected behavior

If [Gradle Kotlin DSL](https://docs.gradle.org/current/userguide/kotlin_dsl.html) is used, `with_cache` will not be able to generate the key, since gradle file will be named `build.gradle.kts`. This file name should be used as an alternative to `build.gradle` without additional configuration because Kotlin DSL is an official part of Gradle.

**Comment by iynere** [comment]
@moormaan great point. would you like to submit a small PR to fix?

my suggestion: instead of hardcodinig `build.gradle`, create a `cache-key-filename` parameter with a default value of `build.gradle`, & replace `find . -name 'build.gradle' | sort | xargs cat | shasum | awk '{print $1}' > /tmp/gradle_cache_seed`

with `find . -name '<<parameters.cache-key-filename>>' | sort | xargs cat | shasum | awk '{print $1}' > /tmp/gradle_cache_seed`:

https://github.com/CircleCI-Public/circleci-orbs/blob/staging/src/gradle/orb.yml#L94

**Comment by KyleTryon** [comment]
Issue migrated to new Repo: https://github.com/CircleCI-Public/gradle-orb/issues/3

**Comment by KyleTryon** [comment]
> @moormaan great point. would you like to submit a small PR to fix?
> 
> my suggestion: instead of hardcodinig `build.gradle`, create a `cache-key-filename` parameter with a default value of `build.gradle`, & replace `find . -name 'build.gradle' | sort | xargs cat | shasum | awk '{print $1}' > /tmp/gradle_cache_seed`
> 
> with `find . -name '<<parameters.cache-key-filename>>' | sort | xargs cat | shasum | awk '{print $1}' > /tmp/gradle_cache_seed`:
> 
> https://github.com/CircleCI-Public/circleci-orbs/blob/staging/src/gradle/orb.yml#L94
