### ISSUE TITLE
Node orb: use package manager lockfiles

### ISSUE THREAD

**Issue by iynere** [CircleCI-Public/circleci-orbs#84]
Node's Orb should rely on package manager lockfiles instead and if you choose `yarn: true` to be using `yarn.lock` as `cache-key` for the `with-cache` command.

(via https://twitter.com/tunnckoCore/status/1072932605979447296)

**Comment by tunnckoCore** [comment]
The thing is how can we access the `parameters` from the `install-package-manager` command. And why not use some "regular" "template" for those dynamic parts?

**Comment by tunnckoCore** [comment]
> is there a reason to wipe the local node_modules/ directory if the lockfile has changed?

Oh yeah, definitely. I think both will warn you about that anyway. So it's always better to clean it up.

**Comment by wyardley** [comment]
I would also suggest that there should be a restore-only option... having only the option that both restores the cache and saves it seems less useful when you break things up into multiple steps, unless I'm missing something.

We ended up just re-implementing what we had before, rather than using `with-cache`.

Orbs don't currently support orb-level params, right? That would be ideal for something like this. Especially since, if you override a param, you'd currently have to do that _every_ time you invite a command like `with-cache`, right?

**Comment by hutson** [comment]
> Oh yeah, definitely. I think both will warn you about that anyway. So it's always better to clean it up. - @tunnckoCore 

Really? My experience is to start every day with `git pull` followed by `yarn install` to ensure my local `node_modules` is sync'd with any changes in my project's `yarn.lock` file.

I don't remember ever seeing a warning. By wiping the cache on every lockfile change, we're basically doing `git pull && rm -rf node_modules && yarn install` which I don't feel is intuitive if I were to do that myself locally.

> Orbs don't currently support orb-level params, right? - @wyardley 

They do not, to my knowledge.

**Comment by KyleTryon** [comment]
Closing due to length of inactivity. The Node orb has since been moved to this repository: https://github.com/CircleCI-Public/node-orb

Please forward any issues or PRs to this repo. Thank you
